import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {installPatchViewer} from './patch-viewer.js';
const nativeFetch=window.fetch.bind(window);
let collection=null;
try{const response=await nativeFetch('/api/datasets');if(response.ok)collection=await response.json();}catch{}
const requestedDataset=new URLSearchParams(location.search).get('dataset');
const selectedDataset=collection?(collection.datasets.some(d=>d.id===requestedDataset)?requestedDataset:collection.default):null;
const datasetBase=selectedDataset?'/d/'+encodeURIComponent(selectedDataset):'';
const overviewLink=document.createElement('a');overviewLink.className='button';overviewLink.textContent='四档强度总览 ↗';overviewLink.href='/overview.html'+(selectedDataset?'?dataset='+encodeURIComponent(selectedDataset):'');document.querySelector('header').append(overviewLink);
const fetch=(url,options)=>nativeFetch(typeof url==='string'&&url.startsWith('/api/')?datasetBase+url:url,options);
const $=id=>document.getElementById(id);
if(collection){document.querySelector('header h1').insertAdjacentHTML('afterend','<select id="dataset-select" aria-label="选择建筑数据集"></select>');for(const d of collection.datasets){const option=document.createElement('option');option.value=d.id;option.textContent=`${d.name} · ${d.id} · ${d.count}版本`;$('dataset-select').append(option);}$('dataset-select').value=selectedDataset;$('dataset-select').onchange=async()=>{if(saving){$('dataset-select').value=selectedDataset;return;}if(ready&&$('note').value!==(saved[records[index].variant]?.note||'')){await save(saved[records[index].variant]?.scale??null);if($('save-state').textContent.startsWith('保存失败')){$('dataset-select').value=selectedDataset;return;}}location.href='/?dataset='+encodeURIComponent($('dataset-select').value);};document.querySelector('header a').href=datasetBase+'/api/export';}
const upgradeStyle=document.createElement('link');upgradeStyle.rel='stylesheet';upgradeStyle.href='/upgrade.css';document.head.append(upgradeStyle);
document.querySelector('.rating-heading').insertAdjacentHTML('afterend',`<div class="score-summary"><div>机器建议<strong id="machine-score">—</strong><small>诊断规则 · 临时建议</small></div><div>人工评分<strong id="human-score">未确认</strong><button id="clear-human">撤销人工分</button></div><div class="effective-card">训练采用<strong id="effective-score">—</strong><small id="effective-source"></small></div></div><details class="machine-explanation"><summary>机器评分依据</summary><span id="machine-reason"></span></details>`);
document.querySelector('.hint').insertAdjacentHTML('afterend',`<details class="asset-info"><summary id="asset-summary">模型概要</summary><div id="asset-details"></div><label>本地资产路径<input id="asset-path" readonly aria-label="本地资产路径"></label></details>`);
document.querySelector('aside').insertAdjacentHTML('afterend','<div id="sidebar-grip" class="grip vertical" role="separator" aria-label="调整队列宽度" tabindex="0"></div>');
$('left').insertAdjacentHTML('afterend','<div id="viewer-grip" class="grip vertical" role="separator" aria-label="调整左右模型宽度" tabindex="0"></div>');
document.querySelector('.rating').insertAdjacentHTML('beforebegin','<div id="height-grip" class="grip horizontal" role="separator" aria-label="调整模型区域高度" tabindex="0"></div>');
$('right').append(document.querySelector('.score-summary'));
$('right').insertAdjacentHTML('beforeend','<div id="compact-score" aria-label="评分摘要"></div>');
document.querySelector('.navigation').append($('clear-human'));
$('filter').insertAdjacentHTML('afterend',`<label class="filter-label" for="scale-filter">按采用分数筛选</label><select id="scale-filter" aria-label="按scale筛选"><option value="all">全部 scale</option><option value="1">scale1</option><option value="2">scale2</option><option value="3">scale3</option><option value="4">scale4</option><option value="5">scale5</option></select><label class="filter-label" for="type-filter">按退化类型筛选</label><select id="type-filter" aria-label="按退化类型筛选"><option value="all">全部类型</option><option value="clean">Clean</option><option value="combined">全部组合退化</option></select><small id="filter-count"></small>`);
document.querySelector('.asset-info').append(document.querySelector('.machine-explanation'));
const compactStyle=document.createElement('link');compactStyle.rel='stylesheet';compactStyle.href='/compact.css';document.head.append(compactStyle);
const summaryStyle=document.createElement('link');summaryStyle.rel='stylesheet';summaryStyle.href='/summary.css';document.head.append(summaryStyle);
let split=.5;
function resizeGrip(id,apply){const g=$(id);g.onpointerdown=e=>{g.setPointerCapture(e.pointerId);e.preventDefault();g.onpointermove=apply;};g.onpointerup=g.onpointercancel=()=>{g.onpointermove=null;};g.onkeydown=e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const rect=g.getBoundingClientRect();apply({clientX:rect.x+(e.key==='ArrowLeft'?-20:20),clientY:rect.y+(e.key==='ArrowUp'?-20:20)});}};}
resizeGrip('sidebar-grip',e=>{document.querySelector('aside').style.width=Math.max(170,Math.min(450,e.clientX))+'px';});
resizeGrip('viewer-grip',e=>{const box=$('viewers').getBoundingClientRect();split=Math.max(.2,Math.min(.8,(e.clientX-box.left)/box.width));$('left').style.flex=split;$('right').style.flex=1-split;});
resizeGrip('height-grip',e=>{const box=$('viewers').getBoundingClientRect();$('viewers').style.flex='none';$('viewers').style.height=Math.max(200,Math.min(900,e.clientY-box.top-60))+'px';});
const names={clean:'原始 Clean',geometry_missing:'几何缺失',geometry_artifacts:'几何噪声 / 伪影',mesh_simplification_qem:'网格简化 QEM',geometry_smoothing:'过度平滑',position_quantization:'坐标量化',texture_blur_resolution_loss:'纹理分辨率损失',texture_compression:'纹理 JPEG 压缩',texture_missing_occlusion:'纹理区域缺失',texture_misalignment_uv:'纹理错位 / 重影',texture_seam_radiometric:'曝光 / 色差接缝',combined_qem_downsample:'简化 + 降采样',combined_position_jpeg:'坐标量化 + JPEG',combined_qem_uv_jpeg:'简化 + UV + JPEG',combined_hole_missing:'几何缺失 + 纹理缺失',combined_noise_ghost:'噪声 + 重影',combined_smooth_downsample:'平滑 + 降采样',combined_hole_ghost:'几何缺失 + 重影',combined_downsample_seam:'降采样 + 色差',combined_qem_jpeg:'简化 + JPEG'};
const label=r=>names[r.variant.replace(/_level\d$/,'')]||r.variant;
const detail=r=>r.variant.match(/level(\d)$/)?`生成强度 ${r.variant.match(/level(\d)$/)[1]} / 4`:(r.variant==='clean'?'质量参考 · 同样可评分':'组合退化');
let data,records,saved,index=0,ready=false,saving=false,request=0,origin,extent,wire=false,currentObject;
const loader=new GLTFLoader();
const originalLoad=loader.loadAsync.bind(loader);loader.loadAsync=url=>originalLoad(datasetBase+url);
// Bootstrap controls stay inert until the clean coordinate frame is available.
document.addEventListener('pointerdown',e=>{if(!origin){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('click',e=>{if(!origin){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('keydown',e=>{if(!origin){e.preventDefault();e.stopImmediatePropagation();}},true);
function panel(id){const scene=new THREE.Scene();scene.background=new THREE.Color('#e8edf2');const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;$(id).append(renderer.domElement);const camera=new THREE.PerspectiveCamera(40,1,.01,10000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=false;scene.add(new THREE.HemisphereLight(0xffffff,0xc4c9d1,2.4));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(1,2,3);scene.add(sun);new ResizeObserver(()=>{const {width,height}=$(id).getBoundingClientRect();if(!width||!height)return;renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}).observe($(id));return {scene,renderer,camera,controls};}
const left=panel('canvas-left'),right=panel('canvas-right');let syncing=false;
installPatchViewer({left,right,getClean:()=>left.scene.children.find(o=>!o.isLight),getCurrent:()=>currentObject,getVariant:()=>records[index].variant,isReady:()=>ready,apiFetch:fetch});
for(const [a,b] of [[left,right],[right,left]])a.controls.addEventListener('change',()=>{if(syncing)return;syncing=true;b.camera.position.copy(a.camera.position);b.camera.quaternion.copy(a.camera.quaternion);b.camera.up.copy(a.camera.up);b.controls.target.copy(a.controls.target);b.controls.update();syncing=false;});
function animate(){requestAnimationFrame(animate);left.renderer.render(left.scene,left.camera);right.renderer.render(right.scene,right.camera);}animate();
function view(direction=[1,.65,1]){for(const p of [left,right]){p.camera.up.set(0,1,0);p.camera.near=extent/10000;p.camera.far=extent*100;p.camera.position.copy(new THREE.Vector3(...direction).normalize().multiplyScalar(extent*1.9));p.camera.updateProjectionMatrix();p.controls.target.set(0,0,0);p.controls.update();}}
function dispose(object){object.traverse(o=>{if(o.geometry)o.geometry.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]))if(m){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});}
function applyWire(object){object.traverse(o=>{if(o.isMesh)for(const m of (Array.isArray(o.material)?o.material:[o.material]))m.wireframe=wire;});}
function refresh(){
 const current=records[index],human=saved[current.variant]?.scale,machine=data.machine_scores[current.variant]?.scale;
 $('compact-score').textContent=`机器 ${machine??'—'} ｜ 人工 ${human??'—'} ｜ 采用 ${human??machine??'—'}（${human!=null?'人工':'机器'}）`;
 const count=records.filter(r=>saved[r.variant]?.scale).length;$('count').textContent=`${count} / ${records.length}`;document.querySelector('.progress>span').textContent='人工已确认';$('progress').value=count;$('progress').max=records.length;
 const q=$('search').value.toLowerCase(),filter=$('filter').value,scale=$('scale-filter').value;
 const candidates=records.filter(r=>{const s=saved[r.variant],m=data.machine_scores[r.variant];return !(filter==='pending'&&s?.scale||filter==='uncertain'&&!s?.uncertain)&&(scale==='all'||(s?.scale??m?.scale)===Number(scale))&&`${label(r)} ${r.variant}`.toLowerCase().includes(q);});
 const selectedType=$('type-filter').value,counts=new Map();let combinations=0;
 for(const r of candidates){const key=r.variant.replace(/_level\d$/,'');counts.set(key,(counts.get(key)||0)+1);if(key.startsWith('combined_'))combinations++;}
 $('type-filter').replaceChildren();
 const addType=(value,text,n)=>{const option=document.createElement('option');option.value=value;option.textContent=`${text}（${n}）`;$('type-filter').append(option);};
 addType('all','全部类型',candidates.length);
 if(counts.has('clean'))addType('clean','Clean',counts.get('clean'));
 if(combinations)addType('combined','全部组合退化',combinations);
 for(const [key,n] of counts)if(key!=='clean')addType(key,names[key]||key,n);
 $('type-filter').value=Array.from($('type-filter').options).some(o=>o.value===selectedType)?selectedType:'all';
 const type=$('type-filter').value;$('list').replaceChildren();
 records.forEach((r,i)=>{const s=saved[r.variant],m=data.machine_scores[r.variant];if(filter==='pending'&&s?.scale||filter==='uncertain'&&!s?.uncertain)return;if(scale!=='all'&&(s?.scale??m?.scale)!==Number(scale))return;if(type!=='all'&&(type==='combined'?!r.variant.startsWith('combined_'):r.variant.replace(/_level\d$/,'')!==type))return;if(!`${label(r)} ${r.variant}`.toLowerCase().includes(q))return;const b=document.createElement('button');b.className=`sample ${i===index?'active':''} ${s?.scale?'rated':''}`;b.innerHTML=`<span class="number">${String(i+1).padStart(2,'0')}</span><span class="name">${label(r)}<small>${detail(r)}</small></span><span class="badge">${s?.scale?'人 '+s.scale:'机 '+(m?.scale??'—')}${s?.uncertain?' ?':''}</span>`;b.onclick=()=>select(i);$('list').append(b);});
 $('filter-count').textContent=`筛选结果 ${$('list').children.length} / ${records.length}`;
}
$('scale-filter').onchange=refresh;$('type-filter').onchange=refresh;
function form(){const r=records[index],s=saved[r.variant],m=data.machine_scores[r.variant],effective=s?.scale??m?.scale;$('note').value=s?.note||'';$('uncertain').checked=!!s?.uncertain;document.querySelectorAll('[data-grade]').forEach(b=>{b.classList.toggle('active',s?.scale===+b.dataset.grade);b.classList.toggle('machine-selected',!s?.scale&&m?.scale===+b.dataset.grade);b.disabled=!ready||saving;});$('save-state').textContent=s?.scale?`人工已保存 · scale${s.scale}`:`默认机器建议 · scale${m?.scale??'—'}`;$('machine-score').textContent=m?`scale${m.scale}`:'暂无';$('human-score').textContent=s?.scale?`scale${s.scale}`:'未确认';$('effective-score').textContent=effective?`scale${effective}`:'未评分';$('effective-source').textContent=s?.scale?'来源：人工 · 优先采用':'来源：机器 · 等待人工复核';$('machine-reason').textContent=m?`${m.reason}。${m.note}`:'尚无机器分';$('clear-human').disabled=!s?.scale||saving;$('asset-summary').textContent=`模型概要 · 顶点 ${(r.vertex_count??0).toLocaleString()} · 三角面 ${(r.face_count??0).toLocaleString()} · 贴图 ${r.image_count??'—'}`;$('asset-details').textContent=`建筑 ${r.asset_id} ｜ ${r.variant} ｜ 内容哈希 ${r.content_digest.slice(0,16)}…`;$('asset-path').value=r.gltf_path;}
async function select(i){if(saving||i<0||i>=records.length)return;index=i;ready=false;const turn=++request;const r=records[i];$('title').textContent=label(r);$('position').textContent=`${i+1} / ${records.length} · ${detail(r)}`;$('loading').classList.remove('hidden');$('loading').textContent='正在载入模型与贴图…';$('model-state').textContent='加载中';refresh();form();try{const gltf=await loader.loadAsync(`/assets/${r.variant}/model.gltf`);if(turn!==request){dispose(gltf.scene);return;}if(currentObject){right.scene.remove(currentObject);dispose(currentObject);}currentObject=gltf.scene;currentObject.position.sub(origin);right.scene.add(currentObject);applyWire(currentObject);ready=true;$('loading').classList.add('hidden');$('model-state').textContent='视角已同步';form();}catch(e){if(turn!==request)return;$('loading').textContent='加载失败：请检查移动硬盘，刷新后重试';console.error(e);}}
async function save(scale,advance=false){if(!ready||saving)return;const r=records[index],at=index;const note=$('note').value,uncertain=$('uncertain').checked;saving=true;form();$('note').value=note;$('uncertain').checked=uncertain;$('save-state').textContent='正在保存…';try{const response=await fetch('/api/score',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':data.token},body:JSON.stringify({id:r.variant,digest:r.content_digest,scale,note,uncertain})});const result=await response.json();if(!response.ok)throw Error(result.error);saved[r.variant]=result.score;saving=false;refresh();form();if(advance&&$('auto').checked&&index===at&&index<records.length-1)select(index+1);}catch(e){saving=false;form();$('note').value=note;$('uncertain').checked=uncertain;$('save-state').textContent='保存失败，请重试：'+e.message;}}
$('note').addEventListener('change',()=>save(saved[records[index].variant]?.scale??null));$('uncertain').onchange=()=>save(saved[records[index].variant]?.scale??null);
$('clear-human').onclick=()=>save(null);
document.querySelectorAll('[data-grade]').forEach(b=>b.onclick=()=>save(+b.dataset.grade,true));$('search').oninput=refresh;$('filter').onchange=refresh;$('previous').onclick=()=>select(index-1);$('next').onclick=()=>select(index+1);$('reset').onclick=()=>view();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view({front:[0,0,1],side:[1,0,0],top:[0,1,.001]}[b.dataset.view]));$('wire').onclick=()=>{wire=!wire;left.scene.traverse(o=>{if(o.isMesh)applyWire(o)});if(currentObject)applyWire(currentObject);$('wire').classList.toggle('active',wire);};$('reference').onclick=()=>{$('viewers').classList.toggle('solo');$('reference').textContent=$('viewers').classList.contains('solo')?'显示参考':'隐藏参考';};
// Keep note editing from firing a competing blur-save before a grade click.
document.querySelectorAll('[data-grade]').forEach(b=>b.addEventListener('pointerdown',e=>e.preventDefault()));
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key>='1'&&e.key<='5')save(+e.key,true);if(e.key==='ArrowRight'){e.preventDefault();select(index+1);}if(e.key==='ArrowLeft'){e.preventDefault();select(index-1);}if(e.key.toLowerCase()==='r')view();if(e.key.toLowerCase()==='c')$('reference').click();});
try{data=await(await fetch('/api/session')).json();records=data.records;saved=data.scores;$('building').textContent=`${data.building} · 本地审阅 / ${data.revision??'process_v2'}`;const clean=await loader.loadAsync('/assets/clean/model.gltf');const box=new THREE.Box3().setFromObject(clean.scene);origin=box.getCenter(new THREE.Vector3());extent=box.getSize(new THREE.Vector3()).length();clean.scene.position.sub(origin);left.scene.add(clean.scene);view();const requestedVariant=new URLSearchParams(location.search).get('variant');await select(Math.max(0,requestedVariant?records.findIndex(r=>r.variant===requestedVariant):records.findIndex(r=>!saved[r.variant]?.scale)));}catch(e){$('loading').textContent='初始化失败：'+e.message;console.error(e);}
