import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id);
const names={geometry_missing:'几何缺失',geometry_artifacts:'几何噪声 / 伪影',mesh_simplification_qem:'网格简化 QEM',geometry_smoothing:'过度平滑',position_quantization:'坐标量化',texture_blur_resolution_loss:'纹理分辨率损失',texture_compression:'JPEG 压缩',texture_missing_occlusion:'纹理区域缺失',texture_misalignment_uv:'纹理错位 / 重影',texture_seam_radiometric:'曝光 / 色差'};
const query=new URLSearchParams(location.search);let collection=null;
try{const r=await fetch('/api/datasets');if(r.ok)collection=await r.json();}catch{}
const dataset=collection?(collection.datasets.some(d=>d.id===query.get('dataset'))?query.get('dataset'):collection.default):null;
const base=dataset?'/d/'+encodeURIComponent(dataset):'';
for(const d of collection?.datasets??[]){const o=document.createElement('option');o.value=d.id;o.textContent=d.name+' · '+d.id;$('dataset').append(o);}
$('dataset').value=dataset;$('dataset').hidden=!collection;
$('dataset').onchange=()=>location.href='/overview.html?dataset='+encodeURIComponent($('dataset').value);
const reviewURL=variant=>'/?'+new URLSearchParams({...dataset?{dataset}:{},variant}).toString();
$('review').href=reviewURL('clean');
const session=await(await fetch(base+'/api/session')).json();
const renderer=new THREE.WebGLRenderer({canvas:$('render'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;
const loader=new GLTFLoader();const clean=(await loader.loadAsync(base+'/assets/clean/model.gltf')).scene;
const box=new THREE.Box3().setFromObject(clean),origin=box.getCenter(new THREE.Vector3()),extent=box.getSize(new THREE.Vector3()).length();
function dispose(object){object?.traverse(o=>{o.geometry?.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])if(m){for(const t of Object.values(m))if(t?.isTexture)t.dispose();m.dispose();}});}
dispose(clean);
let cells=[],loading=0,generation=0,syncing=false;const queue=[];
const shared={position:new THREE.Vector3(1,.65,1).normalize().multiplyScalar(extent*1.9),target:new THREE.Vector3()};
function syncView(source){if(syncing||!$('sync').checked)return;syncing=true;shared.position.copy(source.camera.position);shared.target.copy(source.controls.target);for(const c of cells)if(c!==source){c.camera.position.copy(shared.position);c.controls.target.copy(shared.target);c.controls.update();}syncing=false;}
function reset(direction){shared.position.set(...direction).normalize().multiplyScalar(extent*1.9);shared.target.set(0,0,0);syncing=true;for(const c of cells){c.camera.position.copy(shared.position);c.controls.target.copy(shared.target);c.controls.update();}syncing=false;}
$('reset').onclick=()=>reset([1,.65,1]);$('top').onclick=()=>reset([0,1,.001]);$('sync').onchange=()=>{if($('sync').checked&&cells.length)syncView(cells[0]);};
function pump(){while(loading<2&&queue.length){const c=queue.shift();c.queued=false;if(!c.visible||c.object||c.loading||c.generation!==generation)continue;c.loading=true;loading++;c.status.textContent='加载中…';loader.loadAsync(base+'/assets/'+c.record.variant+'/model.gltf').then(g=>{if(!c.visible||c.generation!==generation){dispose(g.scene);return;}g.scene.position.sub(origin);c.object=g.scene;c.scene.add(g.scene);c.status.textContent='拖动旋转 · 滚轮缩放';}).catch(()=>{c.status.textContent='加载失败，滚动移出再返回可重试';}).finally(()=>{c.loading=false;loading--;if(c.visible&&!c.object&&c.generation===generation)c.status.textContent='加载未完成，请滚动后重试';pump();});}}
const observer=new IntersectionObserver(entries=>{for(const e of entries){const c=cells.find(x=>x.element===e.target);if(!c)continue;c.visible=e.isIntersecting;if(c.visible&&!c.object&&!c.loading&&!c.queued){c.queued=true;queue.push(c);}else if(!c.visible&&c.object){c.scene.remove(c.object);dispose(c.object);c.object=null;c.status.textContent='按需加载';}}pump();},{root:$('scroll'),threshold:.01});
function addCell(record){const element=document.createElement('article');element.className='card';const meta=document.createElement('div');meta.className='meta';const link=document.createElement('a');link.textContent='比较 / 评分 ↗';link.href=reviewURL(record.variant);meta.append(link,document.createTextNode(record.variant==='clean'?'原模型参照':`强度 ${record.operations[0].level}`));const score=document.createElement('div');score.className='score';const human=session.scores[record.variant]?.scale,machine=session.machine_scores[record.variant]?.scale;score.textContent=`机器 ${machine??'待评'} · 人工 ${human??'—'} · 采用 ${human??machine??'待评'}`;meta.append(score);const parameter=document.createElement('div');parameter.className='parameter';parameter.textContent=`面数 ${record.face_count} · 参数 ${record.operations[0]?.value??'无'}`;meta.append(parameter);const model=document.createElement('div');model.className='model';model.setAttribute('aria-label',record.variant+' 三维视图');const status=document.createElement('span');status.className='status';status.textContent='按需加载';model.append(status);element.append(meta,model);$('grid').append(element);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#e8edf2');scene.add(new THREE.HemisphereLight(0xffffff,0xc4c9d1,2.4));const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(1,2,3);scene.add(sun);const camera=new THREE.PerspectiveCamera(40,255/210,extent/10000,extent*100);camera.position.copy(shared.position);const controls=new OrbitControls(camera,model);controls.target.copy(shared.target);controls.update();const c={record,element,model,status,scene,camera,controls,generation,visible:false,object:null};cells.push(c);controls.addEventListener('change',()=>syncView(c));observer.observe(element);
}
const kinds=Object.keys(names).filter(k=>session.records.some(r=>r.variant===k+'_level1'));
for(const kind of kinds){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.value=kind;check.onchange=build;label.append(check,document.createTextNode(names[kind]));$('types').append(label);}
function build(){generation++;observer.disconnect();for(const c of cells){c.controls.dispose();dispose(c.object);}cells=[];queue.length=0;$('grid').replaceChildren();const chosen=Array.from($('types').querySelectorAll('input:checked')).map(i=>i.value);$('grid').style.gridTemplateColumns=`84px repeat(${chosen.length+1},255px)`;for(const text of ['强度','原模型参照',...chosen.map(k=>names[k])]){const h=document.createElement('div');h.className='heading';h.textContent=text;$('grid').append(h);}for(let level=1;level<=4;level++){const label=document.createElement('div');label.className='level';label.textContent=`强度 ${level}`;const note=document.createElement('small');note.textContent=`期望 scale${5-level} ≠ 实评分`;label.append(note);$('grid').append(label);addCell(session.records.find(r=>r.variant==='clean'));for(const kind of chosen){const record=session.records.find(r=>r.variant===kind+'_level'+level);if(record)addCell(record);else{const empty=document.createElement('div');empty.textContent='本档未生成';$('grid').append(empty);}}}$('state').textContent=`${chosen.length} 类 × 4 档 · 评分只读`;}
build();
function frame(){requestAnimationFrame(frame);renderer.setSize(innerWidth,innerHeight,false);renderer.setScissorTest(false);renderer.clear();renderer.setScissorTest(true);const clip=$('scroll').getBoundingClientRect();for(const c of cells){if(!c.visible||!c.object)continue;const r=c.model.getBoundingClientRect();const left=Math.max(0,r.left,clip.left),right=Math.min(innerWidth,r.right,clip.right),top=Math.max(r.top,clip.top),bottom=Math.min(innerHeight,r.bottom,clip.bottom);if(right<=left||bottom<=top)continue;c.camera.aspect=r.width/r.height;c.camera.updateProjectionMatrix();renderer.setViewport(r.left,innerHeight-r.bottom,r.width,r.height);renderer.setScissor(left,innerHeight-bottom,right-left,bottom-top);renderer.render(c.scene,c.camera);}}frame();
